# Generated by Django 4.2.4 on 2023-09-29 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomPattern',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='bottom_patterns/')),
                ('details', models.TextField(max_length=300, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DressType',
            fields=[
                ('dress_type', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='dresses/')),
                ('details', models.TextField(max_length=300, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('fabric_image', models.ImageField(upload_to='media/fabrics/')),
                ('details', models.TextField(max_length=300, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopPattern',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='top_patterns/')),
                ('details', models.TextField(max_length=300, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('dress_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customadmin.dresstype')),
            ],
        ),
        migrations.CreateModel(
            name='SleevesPattern',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='sleeves_patterns/')),
                ('details', models.TextField(max_length=300, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('dress_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customadmin.dresstype')),
            ],
        ),
        migrations.CreateModel(
            name='NeckPattern',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='neck_patterns/')),
                ('details', models.TextField(max_length=300, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('dress_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.dresstype')),
            ],
        ),
        migrations.CreateModel(
            name='Designs',
            fields=[
                ('design_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('bottom_pattern', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bottom_pattern', to='customadmin.bottompattern')),
                ('dress_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customadmin.dresstype')),
                ('fabric1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabric1', to='customadmin.fabric')),
                ('neck_pattern', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='neck_pattern', to='customadmin.neckpattern')),
                ('sleeves_pattern', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sleeves_pattern', to='customadmin.sleevespattern')),
                ('top_pattern', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='top_pattern', to='customadmin.toppattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bottompattern',
            name='dress_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customadmin.dresstype'),
        ),
    ]
