# Generated by Django 4.2.4 on 2023-10-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottompattern',
            old_name='custom_id',
            new_name='bottom_id',
        ),
        migrations.RenameField(
            model_name='designs',
            old_name='bottom_pattern',
            new_name='bottom_id',
        ),
        migrations.RenameField(
            model_name='designs',
            old_name='fabric1',
            new_name='fabric_id',
        ),
        migrations.RenameField(
            model_name='designs',
            old_name='neck_pattern',
            new_name='neck_id',
        ),
        migrations.RenameField(
            model_name='designs',
            old_name='sleeves_pattern',
            new_name='sleeve_id',
        ),
        migrations.RenameField(
            model_name='fabric',
            old_name='custom_id',
            new_name='fabric_id',
        ),
        migrations.RenameField(
            model_name='neckpattern',
            old_name='custom_id',
            new_name='neck_id',
        ),
        migrations.RenameField(
            model_name='sleevespattern',
            old_name='custom_id',
            new_name='sleeve_id',
        ),
        migrations.RenameField(
            model_name='toppattern',
            old_name='custom_id',
            new_name='top_id',
        ),
    ]
