# Generated by Django 4.2.4 on 2023-09-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
