# Generated by Django 4.2.4 on 2023-09-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
