# Generated by Django 4.2.4 on 2023-10-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_rename_custom_id_bottompattern_bottom_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designs',
            old_name='top_pattern',
            new_name='top_id',
        ),
        migrations.AlterField(
            model_name='bottompattern',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='dresstype',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fabric_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='neckpattern',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='sleevespattern',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='toppattern',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
