# Generated by Django 4.2.4 on 2023-09-14 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0002_fabric_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottompattern',
            name='details',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dress',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dresstype',
            name='details',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='details',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='neckpattern',
            name='details',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sleevespattern',
            name='details',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='toppattern',
            name='details',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
