# Generated by Django 4.2.4 on 2023-10-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_userrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabric',
            old_name='fabric_image',
            new_name='image',
        ),
    ]
