# Generated by Django 4.2.4 on 2023-10-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='address_id',
        ),
    ]
