# Generated by Django 4.2.4 on 2023-10-07 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_rename_delivery_address_order_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='designer_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='designer_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
