# Generated by Django 4.2.4 on 2023-09-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='address_line1',
            field=models.CharField(default='fdsfsdfd', max_length=255),
        ),
    ]
