# Generated by Django 4.2.4 on 2023-09-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_shippingaddress_address_line1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line1',
            field=models.CharField(max_length=255),
        ),
    ]
